{% set name = "tools4rdf" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tools4rdf-{{ version }}.tar.gz
  sha256: 081b1676873b858f038eb8b4caf3fcf9e7b20e1224c0180a0303dc037e588c64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - rdflib
    - pyyaml
    - python-graphviz
    - networkx
    - pandas
    - matplotlib

test:
  imports:
    - tools4rdf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pyscal.org
  summary: python tool for working with ontologies and data models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
